name: Set log entry on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create log entry
        run: echo "toJSON(github.event) > ${{ toJSON(github.event) }}"
