name: Set Commit Status on PR Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Create log entry
        run: echo "toJSON(github.event) > ${{ toJSON(github.event) }}"
      - name: Create status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.review.commit_id }} \
          --header 'authorization: Bearer ${{ secrets.THE_GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "success",
            "context":"pull_request_review_approved",
            "target_url": "${{ github.event.pull_request.html_url }}",
            "description":"The build succeeded!"
            }' \
          --fail-with-body 
