name: Set Commit Status on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create log entry Event
        run: echo "toJSON(github.event) > ${{ toJSON(github.event) }}"
      - name: Create log entry PR
        run: echo "toJSON(github.event.pull_request) > ${{ toJSON(github.event.pull_request) }}"
      - name: Create status
        run: |
          curl --request POST \
          --url ${{ github.event.pull_request.statuses_url }} \
          --header 'authorization: Bearer ${{ secrets.THE_GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "success",
            "context":"pull_request_dev_merged",
            "target_url": "${{ github.event.pull_request.html_url }}",
            "description":"The PR on Dev merged!"
            }' \
          --fail-with-body 
