name: Set Commit Status on PR Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.repository > ${{ github.repository }}"
      - run: echo "github.event.workflow_run.head_commit.id > ${{ github.event.workflow_run.head_commit.id }}"
      - run: echo "secrets.THE_TEST_TOKEN > ${{ secrets.THE_TEST_TOKEN }}"
      - run: echo "github.event.workflow_run.html_url > ${{ github.event.workflow_run.html_url }}"
      - run: echo "github.event.payload.pull_request.html_url > ${{ github.event.payload.pull_request.html_url }}"
      - run: echo "github.event.payload.pull_request.head_commit.id > ${{ github.event.payload.pull_request.head_commit.id }}"
      - run: echo "github.event.payload.pull_request > ${{ github.event.payload.pull_request }}"
      - run: echo "github.event.pull_request.html_url > ${{ github.event.pull_request.html_url }}"
      - run: echo "github.event.pull_request.head_commit.id > ${{ github.event.pull_request.head_commit.id }}"
      - run: echo "toJSON(github.event) > ${{ toJSON(github.event) }}"
      - run: echo "toJSON(github.event.pull_request) > ${{ toJSON(github.event.pull_request) }}"
      - run: echo "toJSON(github.event.workflow_run) > ${{ toJSON(github.event.workflow_run) }}"
      - name: Create status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          --header 'authorization: Bearer ${{ secrets.THE_GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "success",
            "context":"continuous-integration/jenkins",
            "target_url": "${{ github.event.workflow_run.html_url }}",
            "description":"The build succeeded!"
            }' \
          --fail-with-body 
