name: Set log entry on PR Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Create log entry
        run: echo "toJSON(github.event) > ${{ toJSON(github.event) }}"
